#define WIFI_SSID  "GANESH" // "<Your WiFi SSID>"
#define WIFI_PASSWD "ganesh123" //"<Your WiFi Password>"
#define PROJECT_ID "prefab-builder-267610" //"<Your Project ID>"
#define REGION "asia-east1" //"<Your Project's Region>"
#define REGISTRY "iot_sensor" //""<Your Registry name>"
#define DEVICE "sensor_esp_display" //"<Your device name>"
